// Event chronology, evidence, and return paths in isolated desktop/phone contexts.
const path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),fs=require('node:fs');
let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
(async()=>{
 const browser=await playwright.chromium.launch({headless:true,executablePath:process.env.EOG_BROWSER_EXECUTABLE||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined)}),base=process.env.EOG_TIMELINE_TEST_URL||'http://127.0.0.1:8037',checks=[],errors=[];
 const ready=p=>p.waitForFunction(()=>document.body.dataset.timelineReady==='true'),frames=p=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))),check=n=>{checks.push(n);console.log('PASS '+n);};
 try{
  for(const width of [320,390,430,768,1440]){
   const context=await browser.newContext({viewport:{width,height:900},isMobile:width<=430,hasTouch:width<=430,reducedMotion:'reduce'}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/timeline.html');await ready(p);
   assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'26');assert.equal(await p.locator('#tw-view-tabs [data-mode="events"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.tw-event-record').count(),26);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await p.locator('.tw-card-media').count(),0);assert.equal(await p.locator('#tw-records>li').first().getAttribute('data-date'),'2023-10-07');if(width<=430)assert.ok(await p.locator('#tw-records>li').first().evaluate(e=>e.getBoundingClientRect().top)<300);
   check(width+'px: events default, 2023 chronology, compact first card and no overflow');
   await p.locator('#link-event-nasser-hospital').scrollIntoViewIfNeeded();await p.locator('#link-event-nasser-hospital').click();await p.waitForFunction(()=>document.getElementById('tw-reader-dialog').open);const origin=await p.evaluate(()=>history.state.readerOrigin.scroll);
   assert.equal(await p.locator('.tw-evidence-source').count(),2);assert.equal(await p.locator('.tw-event-archive-list li').count(),7);assert.ok((await p.locator('.tw-event-detail').innerText()).includes('February 15, 2024'));for(const link of await p.locator('.tw-evidence-source a').all()){assert.ok((await link.getAttribute('href')).startsWith('https://'));assert.equal(await link.getAttribute('target'),'_blank');}
   await p.locator('.tw-event-archive-list a').first().click();assert.equal(new URL(p.url()).searchParams.get('event'),'event-nasser-hospital');assert.equal(await p.locator('.tw-event-return').count(),1);assert.equal(await p.locator('[data-reader-step]').count(),0);const shared=p.url();
   await p.locator('.tw-detail-top [data-back-event]').click();assert.equal(new URL(p.url()).searchParams.get('selected'),'event-nasser-hospital');await p.locator('[data-reader-step="1"]').click();assert.equal(new URL(p.url()).searchParams.get('selected'),'event-rashid-road-aid');await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.getElementById('tw-reader-dialog').open);await frames(p);assert.ok(Math.abs(await p.evaluate(()=>scrollY)-origin)<=2);
   check(width+'px: cited evidence, archive reading, event return, next event and exact feed return');
   await p.goto(shared);await ready(p);await p.locator('.tw-detail-top [data-back-event]').click();assert.equal(new URL(p.url()).searchParams.get('selected'),'event-nasser-hospital');await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.getElementById('tw-reader-dialog').open);await frames(p);
   check(width+'px: shared archive article retains its parent event');
   await p.goto(base+'/timeline.html');await ready(p);await p.screenshot({path:`/tmp/eog-events-${width}.png`});await p.locator('#tw-view-tabs [data-mode="sources"]').click();assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'1331');await p.locator('#tw-view-tabs [data-mode="events"]').click();assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'26');assert.equal(await p.locator('#tw-active-filters').innerText(),'');
   check(width+'px: one-tap full archive and reset event filters');
   await context.close();
  }
  const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/timeline.html');await ready(p);await p.locator('#tw-period-button').tap();await p.locator('#tw-picker-year').selectOption('2025');await p.locator('#period-2025-08').tap();await p.waitForFunction(()=>!document.getElementById('tw-mobile-date-dialog').open);await frames(p);assert.equal(await p.locator('#tw-records>li').first().getAttribute('id'),'row-event-famine-confirmed');assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'26');check('phone event month picker jumps without hiding other events');
  await p.locator('#tw-search-toggle').tap();await p.locator('#tw-query').fill('Nasser');await p.locator('.tw-search-submit').tap();await frames(p);assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'1');assert.equal(await p.locator('#tw-mobile-search-dialog').evaluate(e=>e.open),false);check('phone event search shows one clear result and dismisses the keyboard sheet');
  await p.goto(base+'/timeline.html?mode=events&selected=event-wck-convoy');await ready(p);assert.ok((await p.locator('.tw-event-detail>.tw-event-date').innerText()).includes('April 1, 2024'));assert.ok((await p.locator('.tw-evidence-list').innerText()).includes('April 2, 2024'));await p.locator('.tw-event-method summary').tap();assert.ok((await p.locator('.tw-event-method').innerText()).includes('AI-assisted'));check('event date, later source publication and AI-assisted source check remain explicit');
  await p.goto(base+'/timeline.html');await ready(p);await p.locator('#tw-latest-reporting').scrollIntoViewIfNeeded();await p.locator('#tw-latest-reporting').tap();assert.equal(new URL(p.url()).searchParams.get('mode'),'sources');assert.equal(await p.locator('#tw-records>li').first().getAttribute('data-date'),'2026-09-30');await p.goBack();await p.waitForFunction(()=>document.getElementById('tw-results-title').dataset.count==='26');check('end of selected milestones leads to latest archive and Back restores events');
  await p.goto(base+'/timeline.html?v=1&at=2026-09-01&limit=1331');await ready(p);assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'1331');assert.equal(await p.locator('#tw-view-tabs [data-mode="sources"]').getAttribute('aria-pressed'),'true');check('existing shared article URLs preserve their original reading view');await context.close();
  assert.deepEqual(errors,[]);check('no event runtime errors');fs.writeFileSync('/tmp/eog-timeline-events-result.json',JSON.stringify({passed:true,checks,widths:[320,390,430,768,1440],errors},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
