// Continuous event chronology, inline evidence and article return paths.
const path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),fs=require('node:fs');
let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
(async()=>{
 const browser=await playwright.chromium.launch({headless:true,executablePath:process.env.EOG_BROWSER_EXECUTABLE||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined)}),base=process.env.EOG_TIMELINE_TEST_URL||'http://127.0.0.1:8037',checks=[],errors=[];
 const ready=p=>p.waitForFunction(()=>document.body.dataset.timelineReady==='true'),frames=p=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))),check=n=>{checks.push(n);console.log('PASS '+n);};
 const expanded=p=>p.waitForSelector('.tw-inline-event');
 const close=async p=>{await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.tw-inline-event'));await frames(p);};
 try{
  for(const width of [320,390,430,768,1440]){
   const context=await browser.newContext({viewport:{width,height:900},isMobile:width<=430,hasTouch:width<=430,reducedMotion:'reduce'}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/timeline.html');await ready(p);
   assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'42');assert.equal(await p.locator('.tw-event-record').count(),42);assert.deepEqual(await p.locator('.tw-year-heading').allTextContents(),['2023','2024','2025','2026']);assert.equal(await p.locator('#tw-period-button').isVisible(),false);assert.equal(await p.locator('#tw-more').isVisible(),false);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await p.locator('.tw-card-media').count(),0);if(width<=430)assert.ok(await p.locator('.tw-event-card').first().evaluate(e=>e.getBoundingClientRect().top)<300);for(const a of await p.locator('#tw-years a').all())assert.ok(await a.evaluate(e=>e.getBoundingClientRect().height)>=44);
   check(width+'px: complete chronology, year headings, simple controls and no overflow');
   await p.locator('#year-2026').click();await frames(p);assert.equal(await p.locator('.tw-event-record').count(),42);assert.equal(await p.locator('#year-2026').getAttribute('aria-current'),'date');assert.ok(await p.locator('#row-event-rafah-reopening').evaluate(e=>e.getBoundingClientRect().top)>=0);assert.ok(await p.locator('#row-event-rafah-reopening').evaluate(e=>e.getBoundingClientRect().top)<260);
   check(width+'px: year links jump through events while retaining the entire history');
   await p.locator('#link-event-nasser-hospital').scrollIntoViewIfNeeded();await p.locator('#link-event-nasser-hospital').focus();await p.keyboard.press('Enter');await expanded(p);await frames(p);const origin=await p.evaluate(()=>history.state.readerOrigin.scroll);
   assert.equal(await p.locator('#tw-reader-dialog').evaluate(e=>e.open),false);assert.equal(await p.locator('#link-event-nasser-hospital').getAttribute('aria-expanded'),'true');assert.equal(await p.locator('.tw-evidence-source').count(),2);assert.equal(await p.locator('.tw-event-archive-list li').count(),7);assert.equal(await p.locator('.tw-further-reading').getAttribute('open'),null);assert.equal(await p.locator('[data-save-event]').count(),0);for(const link of await p.locator('.tw-evidence-source a').all()){assert.ok((await link.getAttribute('href')).startsWith('https://'));assert.equal(await link.getAttribute('target'),'_blank');}
   await p.locator('.tw-further-reading summary').click();await p.locator('.tw-event-archive-list a').first().click();await p.waitForFunction(()=>document.getElementById('tw-reader-dialog').open);assert.equal(new URL(p.url()).searchParams.get('event'),'event-nasser-hospital');const shared=p.url();assert.equal(await p.locator('.tw-inline-event').count(),1);
   await p.goBack();await p.waitForFunction(()=>!document.getElementById('tw-reader-dialog').open);await frames(p);assert.equal(new URL(p.url()).searchParams.get('selected'),'event-nasser-hospital');assert.equal(await p.locator('.tw-further-reading').evaluate(e=>e.open),true);await close(p);assert.equal(await p.locator('#link-event-nasser-hospital').getAttribute('aria-expanded'),'false');assert.equal(await p.evaluate(()=>document.activeElement.id),'link-event-nasser-hospital');assert.ok(Math.abs(await p.evaluate(()=>scrollY)-origin)<=2);
   check(width+'px: keyboard inline expansion, cited evidence, article Back, collapse and exact focus return');
   await p.goto(shared);await ready(p);await p.locator('.tw-detail-top [data-back-event]').click();await p.waitForFunction(()=>!document.getElementById('tw-reader-dialog').open);assert.equal(await p.locator('#inline-event-nasser-hospital').count(),1);await p.locator('.tw-close-inline').click();await p.waitForFunction(()=>!document.querySelector('.tw-inline-event'));assert.equal(new URL(p.url()).searchParams.get('selected'),null);
   check(width+'px: shared archive article returns to its inline event and closes within the page');
   await p.goto(base+'/timeline.html');await ready(p);await p.screenshot({path:`/tmp/eog-simple-${width}.png`});await p.locator('#tw-view-tabs [data-mode="sources"]').click();assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'1331');assert.equal(await p.locator('#tw-period-button').isVisible(),true);await p.locator('#tw-view-tabs [data-mode="events"]').click();assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'42');assert.equal(await p.locator('#tw-active-filters').innerText(),'');
   check(width+'px: secondary archive link retains full research tools and a clear timeline return');
   if(width>=768){await p.locator('#tw-more-button').click();await p.locator('#tw-date-open').click();assert.equal(await p.locator('#tw-mobile-date-dialog').evaluate(e=>e.open),true);assert.equal(await p.locator('#tw-jump').isVisible(),true);await p.keyboard.press('Escape');await frames(p);assert.equal(await p.evaluate(()=>document.activeElement.id),'tw-more-button');check(width+'px: optional precise-date dialog opens and restores its More trigger');}
   await context.close();
  }
  const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/timeline.html');await ready(p);
  await p.locator('#tw-more-button').tap();assert.equal(await p.locator('#tw-refine-toggle').isVisible(),false);assert.equal(await p.locator('#tw-options-open').isVisible(),false);assert.equal(await p.locator('#tw-packet-open').isVisible(),false);await p.locator('#tw-date-open').tap();await p.locator('#tw-picker-year').selectOption('2025');await p.locator('#period-2025-08').tap();await p.waitForFunction(()=>!document.getElementById('tw-mobile-date-dialog').open);await frames(p);assert.equal(await p.locator('.tw-event-record').count(),42);assert.equal(await p.evaluate(()=>document.activeElement.id),'year-2025');assert.ok(await p.locator('#row-event-aid-seeker-killings').evaluate(e=>e.getBoundingClientRect().top)<200);check('phone precise date selection is optional and preserves the full chronology');
  await p.locator('#tw-search-toggle').tap();await p.locator('#tw-query').fill('Hind Rajab');await p.locator('.tw-search-submit').tap();await frames(p);assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'1');assert.equal(await p.locator('#tw-mobile-search-dialog').evaluate(e=>e.open),false);assert.equal(await p.locator('#tw-years a').count(),1);check('phone event search shows clear results and only available year links');
  await p.goto(base+'/timeline.html?mode=events&selected=event-wck-convoy');await ready(p);assert.equal(await p.locator('.tw-inline-event').count(),1);assert.ok((await p.locator('#row-event-wck-convoy .tw-event-date').innerText()).includes('April 1, 2024'));assert.ok((await p.locator('.tw-evidence-list').innerText()).includes('April 2, 2024'));await p.locator('.tw-event-method summary').tap();assert.ok((await p.locator('.tw-event-method').innerText()).includes('AI-assisted'));await p.locator('#link-event-nasser-hospital').scrollIntoViewIfNeeded();await p.locator('#link-event-nasser-hospital').tap();assert.equal(await p.locator('.tw-inline-event').count(),1);assert.equal(await p.locator('#inline-event-wck-convoy').count(),0);await frames(p);const switchedOrigin=await p.evaluate(()=>history.state.readerOrigin.scroll);await p.screenshot({path:'/tmp/eog-simple-inline-390.png'});await p.locator('.tw-close-inline').tap();await p.waitForFunction(()=>!document.querySelector('.tw-inline-event'));await frames(p);assert.equal(await p.evaluate(()=>document.activeElement.id),'link-event-nasser-hospital');assert.ok(Math.abs(await p.evaluate(()=>scrollY)-switchedOrigin)<=2);check('shared events expand inline with honest dates and only one event stays expanded');
  await p.goto(base+'/timeline.html?mode=events&selected=event-detention-torture');await ready(p);assert.match(await p.locator('#row-event-detention-torture .tw-event-date').innerText(),/^Report published/);assert.match(await p.locator('.tw-human-impact').innerText(),/53.*West Bank/s);assert.equal(await p.locator('.tw-human-impact a').getAttribute('target'),'_blank');check('finding publication labels and scoped civilian consequences remain clear');
  await p.goto(base+'/timeline.html?mode=events&selected=event-aid-seeker-killings');await ready(p);assert.match(await p.locator('.tw-human-impact').innerText(),/859.*514.*July 31, 2025/s);assert.ok(await p.locator('.tw-inline-event').evaluate(e=>e.scrollWidth<=e.clientWidth));check('expanded phone evidence retains separate aid-site and convoy-route figures');
  await p.goto(base+'/timeline.html?mode=events&q=incubators');await ready(p);assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'1');assert.equal(await p.locator('.tw-event-record').first().getAttribute('id'),'row-event-al-shifa-destruction');check('shortened previews preserve search across complete accounts and impact details');
  await p.goto(base+'/timeline.html?mode=events&selected=event-reproductive-violence');await ready(p);assert.equal(await p.locator('#row-event-reproductive-violence .tw-event-date').innerText(),'Report published · March 2025');check('uncertain release days retain month precision in the simplified feed');
  await p.goto(base+'/timeline.html?mode=events&at=2026-02-28');await ready(p);await frames(p);assert.equal(await p.locator('.tw-event-record').count(),42);assert.ok(await p.locator('#row-event-regional-crossing-closure').evaluate(e=>e.getBoundingClientRect().top)<200);check('existing event-date URLs land on their event with earlier history still visible');
  await p.locator('#tw-latest-reporting').scrollIntoViewIfNeeded();await p.locator('#tw-latest-reporting').tap();assert.equal(new URL(p.url()).searchParams.get('mode'),'sources');assert.equal(await p.locator('#tw-records>li').first().getAttribute('data-date'),'2026-09-30');await p.goBack();await p.waitForFunction(()=>document.getElementById('tw-results-title').dataset.count==='42');check('end of chronology leads to latest archive and Back restores the event view');
  await p.goto(base+'/timeline.html?mode=events');await ready(p);await p.addStyleTag({content:'html{font-size:200%}'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#link-event-october-7').tap();assert.ok(await p.locator('.tw-inline-event').evaluate(e=>e.scrollWidth<=e.clientWidth));check('event navigation and expanded evidence reflow at 200% text size');
  await p.goto(base+'/timeline.html?mode=events&q=endanger');await ready(p);assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'1');assert.equal(await p.locator('.tw-event-record').first().getAttribute('id'),'row-event-ghf-distribution');check('search includes wording from the visible one-sentence previews');
  await p.goto(base+'/timeline.html?mode=events&q=unmatched-zzzz&selected=event-nasser-hospital');await ready(p);assert.equal(await p.locator('#tw-reader-dialog').evaluate(e=>e.open),true);assert.match(await p.locator('#tw-detail-title').innerText(),/Nasser/);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.getElementById('tw-reader-dialog').open);check('shared events outside search results remain readable through the fallback reader');
  await p.goto(base+'/timeline.html?v=1&at=2026-09-01&limit=1331');await ready(p);assert.equal(await p.locator('#tw-results-title').getAttribute('data-count'),'1331');check('legacy article links preserve their reading view');await context.close();
  const landscape=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),lp=await landscape.newPage();lp.on('pageerror',e=>errors.push(e.message));await lp.goto(base+'/timeline.html?mode=events');await ready(lp);await lp.locator('#year-2026').tap();await frames(lp);assert.equal(await lp.locator('.tw-event-record').count(),42);assert.ok(await lp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await lp.locator('#link-event-rafah-reopening').tap();assert.equal(await lp.locator('.tw-inline-event').count(),1);await lp.locator('.tw-close-inline').scrollIntoViewIfNeeded();await lp.locator('.tw-close-inline').tap();await lp.waitForFunction(()=>!document.querySelector('.tw-inline-event'));check('landscape phone retains year navigation and reachable inline close controls');await landscape.close();
  assert.deepEqual(errors,[]);check('no event runtime errors');fs.writeFileSync('/tmp/eog-timeline-events-result.json',JSON.stringify({passed:true,checks,widths:[320,390,430,768,844,1440],errors},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
