// Requires Playwright; uses the Codex bundled runtime when available.
const path=require('node:path'),os=require('node:os');
let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const {chromium}=playwright;
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.EOG_BROWSER_EXECUTABLE||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined)});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 const page=await context.newPage(),errors=[],remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(process.env.EOG_TIMELINE_TEST_URL||'http://127.0.0.1:8037'))remote.push(r.url());});
 const base=process.env.EOG_TIMELINE_TEST_URL||'http://127.0.0.1:8037';const ready=async()=>page.waitForFunction(()=>document.querySelector('#tw-results-title')?.textContent.includes('source records'));
 const passed=[];const check=(name)=>{passed.push(name);console.log('PASS '+name);};
 try {
 await page.goto(base+'/timeline.html',{waitUntil:'domcontentloaded'});await ready();await page.locator('#tw-auto-load').click();assert.equal(await page.locator('#tw-records>li').count(),30);check('initial collection and bounded list');
 assert.ok(!remote.some(url=>/googletagmanager|translate.google|youtube.com/.test(url)));check('no trackers, translation widgets or external media embeds on startup');assert.equal(await page.locator('#tw-from').inputValue(),'2023-01-01');assert.ok((await page.locator('#tw-records>li').first().getAttribute('data-date')).startsWith('2023'));check('timeline begins in 2023');
 await page.locator('#tw-overview-title').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/eog-timeline-desktop-overview.png'});
 await page.locator('#period-2025').click();assert.equal(await page.locator('#tw-from').inputValue(),'2025-01-01');assert.equal(await page.locator('#tw-to').inputValue(),'2025-12-31');assert.equal(await page.evaluate(()=>document.activeElement.id),'period-2025');
 await page.locator('#period-2025-08').click();assert.equal(await page.locator('#tw-from').inputValue(),'2025-08-01');check('year/month overview, native date controls and focus preservation');
 await page.locator('#tw-clear').click();await page.locator('#tw-query').fill('Nasser Hospital');await page.waitForTimeout(450);const count=await page.locator('#tw-results-title').innerText();assert.notEqual(count,'0 source records');
 const source=await page.locator('#tw-records h3 a').first().getAttribute('data-select');const originalURL=page.url();await page.locator('#tw-records h3 a').first().click();assert.equal(await page.locator('#tw-detail-title').count(),1);assert.ok(page.url().includes(source));await page.screenshot({path:'/tmp/eog-timeline-desktop-detail.png'});
 await page.reload({waitUntil:'domcontentloaded'});await ready();assert.ok(await page.locator('#tw-detail').innerText().then(t=>t.includes('Dates, access and source context')));check('search, deep links and reload restore selected source');
 await page.locator('#tw-detail [data-save]').click();assert.equal(await page.locator('#tw-packet-count').innerText(),'1');await page.locator('#tw-packet-open').click();assert.equal(await page.locator('#tw-packet-list .tw-packet-entry').count(),1);
 await page.locator('#tw-notes').fill('Private test notes');
 const download=page.waitForEvent('download');await page.locator('#tw-download-json').click();const d=await download;const p=await d.path();const exported=JSON.parse(fs.readFileSync(p,'utf8'));assert.equal(exported.sources.length,1);assert.equal(exported.privateNotes,'Private test notes');assert.ok(!page.url().includes('Private'));
 await page.keyboard.press('Escape');assert.equal(await page.locator('#tw-packet-dialog').evaluate(el=>el.open),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'tw-packet-open');check('packet save, JSON export, private notes and native dialog Escape/focus return');
 await page.locator('#tw-query').fill('no-match-zzzz');await page.waitForTimeout(450);assert.ok(await page.locator('#tw-detail').innerText().then(t=>t.includes('outside the active filters')));check('filtered-out selected source remains readable');
 await page.goto(base+'/timeline.html',{waitUntil:'domcontentloaded'});await ready();await page.locator('[data-route="nasser"]').click();assert.equal(await page.locator('#tw-records>li').count(),7);assert.ok(page.url().includes('collection=nasser'));await page.locator('#tw-records h3 a').first().click();assert.equal(await page.locator('.tw-follow li').count(),7);await page.locator('[data-close-detail]').click();await page.waitForTimeout(100);assert.ok(!page.url().includes('selected='));assert.equal(await page.evaluate(()=>document.activeElement.id),'link-'+await page.locator('#tw-records h3 a').first().getAttribute('data-select'));check('reading route, related reporting, Back and source focus return');
 await page.locator('[data-mode="events"]').first().click();assert.ok(await page.locator('#tw-empty').innerText().then(t=>t.includes('reviewed chronology is being built')));await page.locator('#tw-empty [data-mode="sources"]').click();check('unapproved events are withheld with usable source-mode recovery');
 await page.locator('#tw-clear').click();await page.locator('#tw-more').click();assert.equal(await page.locator('#tw-records>li').count(),60);check('load-more retains semantic list and moves focus to first added source');
 await page.locator('#tw-refine-toggle').click();await page.locator('#tw-advanced').evaluate(el=>el.open=true);await page.locator('input[name="publisher"][value="Reuters"]').check();await page.locator('input[name="publisher"][value="BBC"]').check();await page.locator('input[name="theme"][value="health-care"]').check();assert.ok((await page.locator('#tw-results-title').innerText()).match(/\d+ source records/));check('live theme and publisher filters');
 const archive=await context.newPage();await archive.goto(base+'/index.html#articles',{waitUntil:'domcontentloaded'});await archive.waitForFunction(()=>document.querySelector('#research-packet-count')?.textContent==='1');assert.ok(await archive.locator('#research-packet-list').innerText().then(t=>t.includes(exported.sources[0].title)));await archive.evaluate(id=>window.removeFromResearchPacket(id),exported.sources[0].packetId);await page.waitForFunction(()=>document.querySelector('#tw-packet-count').textContent==='0');await page.locator('#tw-records [data-save]').first().click();await archive.waitForFunction(()=>document.querySelector('#research-packet-count')?.textContent==='1');check('existing archive reads timeline packet and changes sync across tabs');await archive.close();
 for(const width of [320,390,430,768,1280,1440]){
  await page.setViewportSize({width,height:900});await page.goto(base+'/timeline.html',{waitUntil:'domcontentloaded'});await ready();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow at ${width}`);
  if(width<=430){await page.locator('#tw-records h3 a').first().click();assert.equal(await page.locator('.tw-results').isVisible(),false);assert.ok(await page.locator('#tw-detail-title').isVisible());await page.screenshot({path:`/tmp/eog-timeline-mobile-${width}.png`});await page.locator('[data-close-detail]').click();await page.waitForTimeout(100);assert.ok(await page.locator('.tw-results').isVisible());}
  check('reflow and reading route at '+width+'px');
 }
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/timeline.html',{waitUntil:'domcontentloaded'});await ready();await page.locator('.site-shell-mobile-button').click();assert.equal(await page.locator('#timeline-main').evaluate(el=>el.inert),true);assert.equal(await page.evaluate(()=>document.activeElement.className),'site-shell-mobile-close');await page.keyboard.press('Escape');assert.equal(await page.locator('#timeline-main').evaluate(el=>el.inert),false);assert.equal(await page.evaluate(()=>document.activeElement.className),'site-shell-mobile-button');check('mobile navigation Escape, background inertness and focus return');
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('#tw-clear').evaluate(el=>getComputedStyle(el).transitionDuration),'0s');check('reduced motion');
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/timeline.html',{waitUntil:'domcontentloaded'});await ready();await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('200% root text enlargement has no horizontal overflow');
 await page.evaluate(()=>document.documentElement.style.fontSize='100%');await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#tw-image-toggle').click();assert.equal(await page.locator('.tw-card-media').first().isVisible(),false);await page.locator('#tw-image-toggle').click();assert.equal(await page.locator('.tw-card-media').first().isVisible(),true);check('image preference preserves complete text browsing');
 await page.locator('#tw-scrubber').fill('31');await page.locator('#tw-scrubber').dispatchEvent('change');assert.equal(await page.locator('#tw-from').inputValue(),'2025-08-01');assert.equal(await page.locator('#tw-scrubber').getAttribute('aria-valuetext'),'August 2025');await page.locator('#tw-scrubber').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tw-from').inputValue(),'2025-09-01');check('month scrubber provides direct and keyboard navigation');
 await page.locator('#tw-clear').click();await page.locator('#tw-auto-load').click();await page.locator('#tw-more').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelectorAll('#tw-records>li').length>=60);check('continuous browsing appends records without rebuilding the existing list');
 assert.ok(await page.locator('.tw-record.is-revealed').count()>0);check('scroll reveal enhancement runs');
 const broken=await context.newPage();await broken.route('**/data/timeline/sources.json',r=>r.abort());await broken.goto(base+'/timeline.html');await broken.waitForSelector('#tw-error:not([hidden])');assert.ok(await broken.locator('#tw-error a').getAttribute('href')==='timeline-sources.html');await broken.close();check('dataset failure provides static recovery');
 const noJS=await browser.newContext({javaScriptEnabled:false});const staticPage=await noJS.newPage();await staticPage.goto(base+'/timeline-sources.html');assert.equal(await staticPage.locator('article').count(),1342);await noJS.close();check('all sources available without JavaScript');
 const fixtureContext=await browser.newContext();const fixturePage=await fixtureContext.newPage();
 const dataset=await (await context.request.get(base+'/data/timeline/sources.json')).json(), supporting=dataset.sources.slice(0,2).map(r=>r.id);
 const fixture={version:1,collections:[],claims:[],revisions:[],events:[{id:'test-event',status:'approved',title:'Automated test fixture',summary:'Fixture verifies year precision and source bundles only.',sourceIds:supporting,themes:['health-care'],review:{reviewer:'Test fixture',reviewedAt:'2026-10-03'},eventTime:{start:'2025-01-01',end:null,precision:'year',label:'2025',rationale:'Synthetic date evidence for automated tests',sourceIds:supporting}}],relationships:supporting.map((id,i)=>({id:'test-relation-'+i,from:id,to:'test-event',type:'reports-on',status:'approved',explanation:'Synthetic test relationship',evidence:[{sourceId:id,locator:'Synthetic fixture'}],review:{reviewer:'Test fixture',reviewedAt:'2026-10-03'}}))};
 await fixturePage.route('**/data/timeline/editorial.json',r=>r.fulfill({json:fixture}));await fixturePage.goto(base+'/timeline.html?mode=events',{waitUntil:'domcontentloaded'});await fixturePage.waitForFunction(()=>document.querySelector('#tw-results-title').textContent==='1 reviewed events');await fixturePage.locator('#tw-records h3 a').click();assert.ok((await fixturePage.locator('#tw-detail').innerText()).includes('Year') || (await fixturePage.locator('#tw-detail').innerText()).includes('year'));await fixturePage.locator('[data-save-event]').click();assert.equal(await fixturePage.locator('#tw-packet-count').innerText(),'2');await fixtureContext.close();check('approved chronology fixtures retain precision and save supporting-source bundles');
 assert.deepEqual(errors,[]);check('no timeline runtime errors');
 fs.writeFileSync('/tmp/eog-timeline-browser-result.json',JSON.stringify({passed:true,checks:passed,widths:[320,390,430,768,1280,1440],errors,imageRequests:remote.length},null,2));
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
