import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import '../assets/research-packet.js';
import {buildSources,filterSources,defaults,parseState,stateURL,civilDate,displayDate,periodCounts,periodRange,cleanSummary,escapeHTML,safeURL,citation,validateEditorial,statusGroup,relatedSources} from '../assets/timeline-core.mjs';
const read=async p=>JSON.parse(await readFile(new URL('../'+p,import.meta.url),'utf8'));
const raw=await read('data/articles.json'),registry=await read('data/timeline/source-registry.json'),data=await read('data/timeline/sources.json'),editorial=await read('data/timeline/editorial.json');
const sources=data.sources;
test('entire corpus is accounted for without touching imported data',()=>{assert.equal(raw.length,1352);assert.equal(sources.length,1342);assert.equal(sources.reduce((n,r)=>n+r.importNumbers.length,0)+data.excluded.length,raw.length);assert.equal(data.duplicateCount,9);assert.equal(data.excluded[0].index,196);assert.equal(new Set(sources.map(r=>r.id)).size,sources.length);assert.equal(new Set(sources.map(r=>r.packetId)).size,sources.length);});
test('source dates are never promoted to event or verified publication dates',()=>{for(const r of sources){assert.equal(r.dateBasis,'Archive date');assert.equal(r.publicationDate,null);assert.equal(r.eventTime,null);}assert.equal(sources.find(r=>r.importNumbers.includes(203)).importedDate,'2001-06-02');assert.ok(sources.find(r=>r.importNumbers.includes(203)).flags.some(f=>f.startsWith('Date differs')));});
test('civil dates reject rollover and remain timezone independent',()=>{assert.equal(civilDate('2025-02-29'),null);assert.equal(civilDate('2024-02-29'),'2024-02-29');assert.equal(displayDate('2025-01-01'),'January 1, 2025');assert.equal(civilDate('2025-1-1'),null);assert.equal(civilDate(''),null);});
test('month and year bounds retain real period lengths',()=>{assert.deepEqual(periodRange('2024-02'),['2024-02-01','2024-02-29']);assert.deepEqual(periodRange('2025'),['2025-01-01','2025-12-31']);});
test('OR within themes and publishers; AND across facets',()=>{const s={...defaults(),themes:['health-care','food-aid'],publishers:['Reuters','BBC']};const matches=filterSources(sources,s);assert.ok(matches.length);assert.ok(matches.every(r=>r.themes.some(t=>s.themes.includes(t))&&s.publishers.includes(r.source)));assert.equal(matches.length,sources.filter(r=>r.themes.some(t=>s.themes.includes(t))&&s.publishers.includes(r.source)&&r.importedDate>='2023-01-01').length);});
test('overview counts and filtered chronology agree',()=>{const records=filterSources(sources,{...defaults(),q:'hospital',from:'2025-01-01',to:'2025-12-31'});assert.equal(periodCounts(records,'month').reduce((n,[,v])=>n+v,0),records.length);});
test('unknown dates stay findable outside explicit date ranges',()=>{const fixture={...sources[0],id:'unknown',importedDate:null};assert.equal(filterSources([fixture],{...defaults(),from:''}).length,1);assert.equal(filterSources([fixture],{...defaults(),from:'2025-01-01'}).length,0);assert.equal(filterSources([fixture],{...defaults(),from:'',dates:'unknown'}).length,1);});
test('same-day ordering is stable regardless of input order',()=>{const a={...sources[0],id:'a'},b={...a,id:'b'};assert.deepEqual(filterSources([b,a],defaults()).map(r=>r.id),['a','b']);assert.deepEqual(filterSources([a,b],{...defaults(),order:'oldest'}).map(r=>r.id),['a','b']);});
test('URL state round trips every public control without private content',()=>{const state={...defaults(),mode:'events',q:'health & care',from:'2025-02-01',to:'2026-09-30',themes:['health-care','life-culture'],publishers:['Reuters','BBC'],types:['Article','Report'],status:'restricted',dates:'review',collection:'nasser',granularity:'day',order:'oldest',selected:sources[0].id,at:'2025-08-14',limit:90};assert.deepEqual(parseState(stateURL(state)),state);assert.ok(!stateURL(state).includes('notes'));});
test('malformed URL parameters fail safely and reversed ranges normalize',()=>{const s=parseState('?from=2026-01-01&to=2025-01-01&themes=fake&limit=Infinity&mode=fake&status=evil');assert.equal(s.from,'2025-01-01');assert.equal(s.to,'2026-01-01');assert.deepEqual(s.themes,[]);assert.equal(s.mode,'sources');assert.equal(s.limit,30);});
test('selected ID stays independent of active filters',()=>{const s={...defaults(),q:'no-match-zzzz',selected:sources[0].id};assert.equal(filterSources(sources,s).length,0);assert.equal(parseState(stateURL(s)).selected,sources[0].id);});
test('artifacts and access errors are removed only from display text',()=>{const original='Stored :contentReference[oaicite:0]{index=0} account.';assert.equal(cleanSummary(original),'Stored  account.');assert.equal(cleanSummary('403 Forbidden'), '');assert.equal(original.includes('oaicite'),true);});
test('text escaping and URL protocol checks prevent markup execution',()=>{assert.equal(escapeHTML('<img src=x onerror="alert(1)">'),'&lt;img src=x onerror=&quot;alert(1)&quot;&gt;');assert.equal(safeURL('javascript:alert(1)'), '');assert.equal(safeURL('data:text/html,hi'),'');assert.ok(safeURL('https://example.com'));});
test('citation formats keep unverified publication dates unknown',()=>{const r={...sources[0],authors:[],importedDate:null};for(const style of ['apa','mla','chicago']){const c=citation(r,style);assert.ok(c.includes('n.d.'));assert.ok(c.includes('publication date awaiting verification'));assert.ok(!c.includes('Archived: https://web.archive.org/web/*'));}assert.ok(citation(r).includes('Author unknown'));assert.ok(citation(r).includes('No preserved copy recorded'));});
test('legacy packet IDs migrate while unknown saved identifiers survive',()=>{const a=raw[0];assert.deepEqual(EogPacket.migrate([EogPacket.aliases(a)[1],'external-id'],raw),[EogPacket.id(a),'external-id']);const b={...a,title:'Metadata correction'};assert.equal(EogPacket.id(a),EogPacket.id(b));});
test('full packet fingerprints do not collide across the corpus',()=>{const lookup=new Map();for(const a of raw){const id=EogPacket.id(a);assert.ok(!lookup.has(id)||lookup.get(id)===a.link);lookup.set(id,a.link);}const a={...raw[0],link:'https://publisher.example/same/long/url-prefix/one'},b={...a,link:'https://publisher.example/same/long/url-prefix/two'};assert.notEqual(EogPacket.id(a),EogPacket.id(b));});
test('permanent source IDs survive title and summary correction',()=>{const corrected=raw.map(a=>({...a,title:a.title+' amended'}));const built=buildSources(corrected,registry,undefined,undefined,undefined,'2026-10-03');const first=built.sources.find(r=>r.url===sources[0].url);assert.equal(first.id,sources[0].id);});
test('future imports are excluded and exact URLs are grouped',()=>{const a=raw[0],testRaw=[a,{...a,title:'Alternate metadata'},{...a,link:'https://future.example',date:'2099-01-01'}];const reg={records:[...registry.records,{id:'future',urls:['https://future.example'],packetId:'future',packetAliases:[]}]};const result=buildSources(testRaw,reg,undefined,undefined,undefined,'2026-10-03');assert.equal(result.sources.length,1);assert.equal(result.sources[0].importNumbers.length,2);assert.equal(result.excluded[0].reason,'future archive date');});
test('blocked and likely-removed results are not confirmed removal',()=>{assert.equal(statusGroup({integrity:{status:'blocked_unknown'}}),'restricted');assert.equal(statusGroup({integrity:{status:'removed_likely'}}),'unchecked');assert.equal(statusGroup({integrity:{status:'confirmed_live'}}),'available');});
test('manual provenance overrides automated observation without exposing notes',()=>{const a=raw[0],reg=registry;const built=buildSources([a],reg,{results:[{id:'check',original:{url:a.link},status:'blocked_unknown',checked_at:'2026-01-01T00:00:00Z'}]},{overrides:{check:{manual_status:'confirmed_live',verified_at:'2026-01-02T00:00:00Z',notes:'private'}}},{records:{}},'2026-10-03').sources[0];assert.equal(statusGroup(built),'available');assert.equal(built.integrity.checkedAt,'2026-01-02T00:00:00Z');assert.ok(!JSON.stringify(built).includes('private'));});
test('wildcard archive URLs are never presented as actual preservation',()=>{const a=raw[0];for(const capture of ['https://web.archive.org/web/*/'+a.link,'https://malicious.example/web/20260101000000/'+a.link]){const r=buildSources([a],registry,undefined,undefined,{records:{[a.link]:{archive_url:capture}}},'2026-10-03').sources[0];assert.equal(r.integrity.captureURL,null);}const actual='https://web.archive.org/web/20260930000000/'+a.link;assert.equal(buildSources([a],registry,undefined,undefined,{records:{[a.link]:{archive_url:actual}}},'2026-10-03').sources[0].integrity.captureURL,actual);});
test('reading routes contain real sources and do not become events',()=>{assert.deepEqual(validateEditorial(editorial,sources),[]);assert.equal(editorial.events.length,26);assert.ok(editorial.collections.every(c=>!editorial.events.some(e=>e.id===c.id)));const selected=sources.find(r=>r.id===editorial.collections[0].sourceIds[0]);assert.equal(relatedSources(selected,sources,editorial.collections).records.length,7);});
test('approval requires date evidence, approved source relations and reviewer',()=>{const bad={events:[{id:'event-bad',status:'approved',eventTime:{start:'2099-01-01',end:'2024-01-01',precision:'day'},sourceIds:['missing']}],relationships:[],collections:[]};const errors=validateEditorial(bad,sources);assert.ok(errors.length>=5);const source=sources[0];const valid={events:[{id:'e',status:'approved',title:'Reviewed title',summary:'Reviewed summary',sourceIds:[source.id],review:{reviewer:'Editor',reviewedAt:'2026-10-03'},eventTime:{start:'2025-01-01',end:null,precision:'year',label:'2025',rationale:'Passage gives year only',sourceIds:[source.id]}}],relationships:[{id:'r',from:source.id,to:'e',type:'reports-on',status:'approved',explanation:'Source passage supports entry',evidence:[{sourceId:source.id,locator:'Paragraph 2'}],review:{reviewer:'Editor',reviewedAt:'2026-10-03'}}],collections:[]};assert.deepEqual(validateEditorial(valid,sources),[]);});

test('interactive defaults begin in 2023 and progress chronologically',()=>{assert.equal(defaults().from,'2023-01-01');assert.equal(defaults().order,'oldest');const records=filterSources(sources,defaults());assert.equal(records.length,1331);assert.ok(records.every(r=>r.importedDate>='2023-01-01'));assert.equal(parseState('?from=2001-01-01').from,'2023-01-01');});

test('shared packet identity survives a reviewed URL alias change',()=>{const original=raw[0],stable=EogPacket.id(original),changed={...original,link:'https://example.org/corrected-permanent-source-url'};EogPacket.configure({[changed.link]:stable});assert.equal(EogPacket.id(changed),stable);assert.ok(EogPacket.aliases(changed).includes(stable));assert.deepEqual(EogPacket.migrate([stable],[changed]),[stable]);EogPacket.configure({});});

test('reading date is shareable, validated and independent of date filters',()=>{const state={...defaults(),at:'2025-08-14'};assert.deepEqual(parseState(stateURL(state)),state);assert.equal(filterSources(sources,state).length,1331);assert.equal(parseState('?at=2025-02-31').at,'');assert.equal(parseState('?at=2001-01-01').at,'2023-01-01');});


test('fresh visits open events while old article links preserve their view',()=>{assert.equal(parseState('').mode,'events');for(const query of ['?v=1','?at=2026-09-01','?from=2024-01-01','?q=hospital'])assert.equal(parseState(query).mode,'sources');assert.equal(parseState('?mode=events&at=2024-01-26').mode,'events');});
test('event parent survives public link round trip without private notes',()=>{const s={...defaults(),selected:sources[0].id,event:'event-nasser-hospital',at:'2024-02-15'};assert.deepEqual(parseState(stateURL(s)),s);});
test('all published events carry valid primary references and honest review attribution',()=>{assert.equal(editorial.references.length,31);for(const e of editorial.events){assert.ok(e.eventTime.start>='2023-01-01');assert.ok(e.sourceIds.length);assert.ok(e.sourceIds.every(id=>editorial.references.some(r=>r.id===id)));assert.ok(e.review.reviewer.includes('AI-assisted'));assert.ok((e.archiveSourceIds||[]).every(id=>sources.some(r=>r.id===id)));}assert.deepEqual(validateEditorial(editorial,sources),[]);});
test('invalid reference links and dangling related archive records fail validation',()=>{const broken=structuredClone(editorial);broken.references[0].url='javascript:alert(1)';broken.events[0].archiveSourceIds=['not-an-archive-record'];assert.ok(validateEditorial(broken,sources).length>=2);});
test('event time remains distinct from later supporting publication',()=>{const e=editorial.events.find(e=>e.id==='event-wck-convoy');assert.equal(e.eventTime.start,'2024-04-01');assert.ok(editorial.references.filter(r=>e.sourceIds.includes(r.id)).some(r=>r.publicationDate>'2024-04-01'));});
