// Isolated browser contexts keep the user's saved sources and notes untouched.
const path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),fs=require('node:fs');
let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
(async()=>{
 const browser=await playwright.chromium.launch({headless:true,executablePath:process.env.EOG_BROWSER_EXECUTABLE||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined)});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,reducedMotion:'reduce'});
 const page=await context.newPage(),errors=[],remote=[],passed=[];
 const base=process.env.EOG_TIMELINE_TEST_URL||'http://127.0.0.1:8037';
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base))remote.push(r.url());});
 const check=name=>{passed.push(name);console.log('PASS '+name);};
 const ready=async()=>page.waitForFunction(()=>/source records|reviewed events/.test(document.querySelector('#tw-results-title')?.textContent||''));
 const fresh=async(query='')=>{await page.goto(base+'/timeline.html'+query,{waitUntil:'domcontentloaded'});await ready();};
 const options=async()=>{if(!await page.locator('#tw-view-options').evaluate(el=>el.open))await page.locator('#tw-view-options>summary').click();};
 const filters=async()=>{if(await page.locator('#tw-refinement').evaluate(el=>el.hidden))await page.locator('#tw-refine-toggle').click();};
 const closeReader=async()=>{await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#tw-reader-dialog').open);};
 try{
  await fresh();await options();await page.locator('#tw-auto-load').click();await page.locator('#tw-view-options>summary').click();
  assert.equal(await page.locator('#tw-records>li').count(),30);assert.equal(await page.locator('#tw-from').inputValue(),'2023-01-01');
  assert.equal(await page.locator('#tw-current-period').innerText(),'October 2023');assert.equal(await page.locator('#tw-previous').isDisabled(),true);
  assert.equal(await page.locator('#tw-mode-toolbar').isVisible(),false);check('2023 start, synchronized current month, hidden empty mode and bounded initial list');
  assert.ok(!remote.some(url=>/googletagmanager|translate.google|youtube.com/.test(url)));check('no tracking widgets or external media embeds on startup');
  await page.locator('#tw-next').click();await page.waitForFunction(()=>document.querySelector('#tw-current-period').textContent==='November 2023');
  assert.equal(await page.locator('#tw-results-title').innerText(),'1,331 source records');assert.equal(await page.locator('#tw-from').inputValue(),'2023-01-01');assert.equal(await page.locator('#tw-to').inputValue(),'');assert.equal(await page.locator('#tw-records>li').count(),30);
  assert.ok((await page.locator('#tw-records>li').first().getAttribute('data-date')).startsWith('2023-11'));check('next month skips empty periods and navigates without filtering or rendering the whole corpus');
  await page.locator('#tw-previous').click();await page.waitForFunction(()=>document.querySelector('#tw-current-period').textContent==='October 2023');check('previous month returns to the preceding populated month');
  await page.locator('#tw-period-button').click();assert.equal(await page.locator('#period-2023-01').isDisabled(),true);assert.equal(await page.locator('#period-2023-10').getAttribute('aria-pressed'),'true');
  await page.keyboard.press('Escape');assert.equal(await page.locator('#tw-date-picker').evaluate(el=>el.open),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'tw-period-button');check('date chooser communicates unavailable months and Escape returns focus');
  await page.locator('#tw-period-button').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#tw-date-picker').evaluate(el=>el.open),true);await page.locator('#tw-jump').fill('2023-01-01');await page.locator('#tw-jump-button').click();assert.equal(await page.locator('#tw-current-period').innerText(),'October 2023');assert.equal(await page.locator('#tw-results-title').innerText(),'1,331 source records');check('keyboard date-picker opening and an empty-date jump select the next available article');
  await page.locator('#period-2025').click();await page.locator('#tw-period-button').click();await page.locator('#tw-picker-year').selectOption('2025');await page.locator('#period-2025-08').click();
  await page.waitForFunction(()=>document.querySelector('#tw-current-period').textContent==='August 2025');assert.equal(await page.locator('#tw-results-title').innerText(),'1,331 source records');assert.equal(await page.locator('#period-2025').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#tw-date-picker').evaluate(el=>el.open),false);check('year overview and month picker jump to articles while preserving the collection');
  await options();await page.locator('#tw-group').selectOption('day');assert.equal(await page.locator('#tw-records>li').count(),30);assert.ok((await page.locator('#tw-records>li').first().getAttribute('data-date')).startsWith('2025-08'));await page.locator('#tw-group').selectOption('month');await page.locator('#tw-view-options>summary').click();check('grouping in View options preserves the reading window instead of submitting filters');
  const target=page.locator('#tw-records>li').first();await target.scrollIntoViewIfNeeded();
  const origin=await page.evaluate(()=>({scroll:scrollY,ids:[...document.querySelectorAll('#tw-records>li')].map(el=>el.id),rect:document.querySelector('#tw-records>li').getBoundingClientRect().toJSON()}));
  const originId=await page.locator('#tw-records h3 a').first().getAttribute('id');
  await page.locator('#tw-records h3 a').first().click();assert.equal(await page.locator('#tw-reader-dialog').evaluate(el=>el.open),true);
  assert.ok((await page.locator('[data-close-detail]').innerText()).includes('August 2025'));
  assert.deepEqual(await page.locator('#tw-records>li').evaluateAll(els=>els.map(el=>el.id)),origin.ids);
  assert.equal(await page.locator('#tw-records>li').first().evaluate(el=>el.getBoundingClientRect().width),origin.rect.width);check('reading drawer opens without rebuilding or resizing the feed');
  const selected=new URL(page.url()).searchParams.get('selected');await page.locator('[data-reader-step="1"]').click();assert.notEqual(new URL(page.url()).searchParams.get('selected'),selected);
  await closeReader();assert.ok(Math.abs(await page.evaluate(()=>scrollY)-origin.scroll)<=2);assert.equal(await page.evaluate(()=>document.activeElement.id),originId);check('next article and Escape return directly to the original reading position and focus');
  await page.locator('#tw-records h3 a').first().click();await page.goBack();await page.waitForFunction(()=>!document.querySelector('#tw-reader-dialog').open);assert.ok(Math.abs(await page.evaluate(()=>scrollY)-origin.scroll)<=2);check('browser Back closes the reader and restores the feed');
  await page.waitForTimeout(100);await page.locator('#tw-before').hover();
  const oldFirst=await page.locator('#tw-records>li').first().getAttribute('id');const oldTop=await page.locator('#'+oldFirst).evaluate(el=>el.getBoundingClientRect().top);
  await page.locator('#tw-before').click();assert.ok(await page.locator('#tw-records>li').count()>30);assert.ok(Math.abs(await page.locator('#'+oldFirst).evaluate(el=>el.getBoundingClientRect().top)-oldTop)<=3,JSON.stringify({oldTop,newTop:await page.locator('#'+oldFirst).evaluate(el=>el.getBoundingClientRect().top)}));check('loading earlier articles preserves the visible anchor');
  await page.locator('#'+oldFirst).scrollIntoViewIfNeeded();const beforeReload=await page.evaluate(()=>scrollY);await page.reload();await ready();await page.waitForTimeout(100);assert.ok(Math.abs(await page.evaluate(()=>scrollY)-beforeReload)<=3,JSON.stringify({beforeReload,after:await page.evaluate(()=>scrollY),entry:await page.evaluate(()=>history.state)}));check('reload resumes the same reading window and scroll position');
  const sharedDate=new URL(page.url()).searchParams.get('at'),shared=new URL(page.url()).search;const sharedPage=await context.newPage();await sharedPage.goto(base+'/timeline.html'+shared);await sharedPage.waitForFunction(()=>document.querySelector('#tw-results-title').textContent.includes('source records'));assert.equal(await sharedPage.locator('#tw-records>li').first().getAttribute('data-date'),sharedDate);await sharedPage.close();check('public date links open at the shared reading date');
  await fresh();await filters();await page.locator('[data-route="nasser"]').click();assert.equal(await page.locator('#tw-records>li').count(),7);assert.ok((await page.locator('#tw-active-filters').innerText()).includes('Nasser'));await page.locator('#tw-records h3 a').first().click();assert.equal(await page.locator('.tw-follow li').count(),7);check('topic collections show an explicit active filter and related reporting');
  const original=await page.locator('.tw-source-link').getAttribute('href');assert.ok(original.startsWith('https://'));assert.equal(await page.locator('.tw-source-link').getAttribute('target'),'_blank');assert.ok((await page.locator('.tw-source-link').innerText()).includes('Open original article'));check('details and the original external article have distinct actions');
  await page.locator('#tw-detail [data-save]').click();await closeReader();await page.locator('#tw-packet-open').click();assert.equal(await page.locator('#tw-packet-list .tw-packet-entry').count(),1);await page.locator('#tw-notes').fill('Private test notes');
  const download=page.waitForEvent('download');await page.locator('#tw-download-json').click();const d=await download,exported=JSON.parse(fs.readFileSync(await d.path(),'utf8'));
  assert.equal(exported.sources.length,1);assert.equal(exported.privateNotes,'Private test notes');assert.ok(!page.url().includes('Private'));await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'tw-packet-open');check('saved sources, export, private notes and dialog focus return');
  const archive=await context.newPage();await archive.goto(base+'/index.html#articles',{waitUntil:'domcontentloaded'});await archive.waitForFunction(()=>document.querySelector('#research-packet-count')?.textContent==='1');assert.ok((await archive.locator('#research-packet-list').innerText()).includes(exported.sources[0].title));await archive.evaluate(id=>window.removeFromResearchPacket(id),exported.sources[0].packetId);await page.waitForFunction(()=>document.querySelector('#tw-packet-count').textContent==='0');await archive.close();check('saved sources remain compatible with the original archive and synchronize across tabs');
  await page.locator('[data-remove-filter="collection"]').click();assert.equal(await page.locator('#tw-results-title').innerText(),'1,331 source records');check('individual filter removal widens the collection');
  await page.locator('#tw-query').fill('hospital');await page.waitForTimeout(400);await filters();await page.locator('#tw-advanced').evaluate(el=>el.open=true);await page.locator('input[name="publisher"][value="Reuters"]').check();await page.locator('input[name="theme"][value="health-care"]').check();
  const filteredCount=await page.locator('#tw-results-title').innerText();assert.ok(!filteredCount.startsWith('0 '));await page.locator('#tw-period-button').click();await page.locator('#tw-latest').click();assert.equal(await page.locator('#tw-results-title').innerText(),filteredCount);assert.ok(new URL(page.url()).searchParams.get('publishers').includes('Reuters'));check('date navigation respects search and publisher/topic filters');
  await page.locator('#tw-refine-toggle').click();await filters();await page.locator('#tw-clear').click();assert.equal(await page.locator('#tw-results-title').innerText(),'1,331 source records');assert.equal(await page.locator('#tw-active-filters').innerText(),'');check('clear all filters restores the collection');
  await page.locator('#tw-query').fill('no-match-zzzz');await page.waitForTimeout(400);assert.ok(await page.locator('#tw-empty').isVisible());assert.equal(await page.locator('#tw-next').isDisabled(),true);assert.equal(await page.locator('#tw-previous').isDisabled(),true);await page.locator('#tw-empty [data-reset]').click();check('empty search disables date navigation and offers recovery');
  const filteredOutId=exported.sources[0].id;await fresh('?q=no-match-zzzz&selected='+filteredOutId);assert.ok((await page.locator('#tw-detail').innerText()).includes('outside the active filters'));await closeReader();check('shared source outside active filters remains readable');
  await fresh('?mode=events');assert.ok((await page.locator('#tw-empty').innerText()).includes('reviewed chronology is being built'));await page.locator('#tw-empty [data-mode="sources"]').click();assert.equal(await page.locator('#tw-mode-toolbar').isVisible(),false);check('legacy empty chronology links recover to source browsing');
  await fresh();await page.locator('#tw-more').click();assert.equal(await page.locator('#tw-records>li').count(),60);assert.ok((await page.evaluate(()=>document.activeElement.id)).startsWith('link-'));check('manual loading appends articles and focuses the first addition');
  for(const width of [320,390,430,768,1280,1440]){
   await page.setViewportSize({width,height:900});await fresh();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow at '+width);
   if(width<=430){assert.ok(await page.locator('#tw-records>li').first().evaluate(el=>el.getBoundingClientRect().top+scrollY)<650);await page.locator('#tw-period-button').click();const bounds=await page.locator('.tw-date-popover').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width);await page.keyboard.press('Escape');}
   const before=await page.locator('#tw-records>li').first().evaluate(el=>el.getBoundingClientRect().width);await page.locator('#tw-records h3 a').first().click();assert.ok(await page.locator('#tw-reader-dialog').isVisible());assert.equal(await page.locator('#tw-records>li').first().evaluate(el=>el.getBoundingClientRect().width),before);await closeReader();
   await page.screenshot({path:`/tmp/eog-timeline-ux-${width}.png`});check('compact content, picker bounds and stable reader at '+width+'px');
  }
  await page.setViewportSize({width:390,height:844});await fresh();await page.locator('.site-shell-mobile-button').click();assert.equal(await page.locator('#timeline-main').evaluate(el=>el.inert),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#timeline-main').evaluate(el=>el.inert),false);check('mobile site menu restores focus and releases the background');
  await page.setViewportSize({width:1440,height:1000});await fresh();await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>document.documentElement.style.fontSize='100%');check('200% text enlargement reflows without horizontal overflow');
  await options();await page.locator('#tw-image-toggle').click();assert.equal(await page.locator('.tw-card-media').first().isVisible(),false);await page.locator('#tw-image-toggle').click();assert.equal(await page.locator('.tw-card-media').first().isVisible(),true);check('view options preserve text-only browsing');
  assert.equal(await page.locator('#tw-refine-toggle').evaluate(el=>getComputedStyle(el).transitionDuration),'0s');check('reduced motion removes interface transitions');
  await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#tw-view-options>summary').click();await page.locator('#tw-records>li').nth(20).scrollIntoViewIfNeeded();await page.waitForTimeout(600);const reading=await page.locator('#tw-current-period').innerText();assert.notEqual(reading,'October 2023');await page.locator('#tw-period-button').click();assert.equal(await page.locator('#tw-picker-year').inputValue(),reading.slice(-4));assert.equal(await page.locator('#tw-months button[aria-pressed="true"]').count(),1);await page.keyboard.press('Escape');check('scrolling synchronizes the date label, year rail and month chooser');
  await fresh();await options();await page.locator('#tw-auto-load').click();await page.locator('#tw-view-options>summary').click();await page.locator('#tw-more').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelectorAll('#tw-records>li').length>=60);assert.ok(await page.locator('.tw-record.is-revealed').count()>0);check('continuous loading and one-time scroll reveals');
  const broken=await context.newPage();await broken.route('**/data/timeline/sources.json',r=>r.abort());await broken.goto(base+'/timeline.html');await broken.waitForSelector('#tw-error:not([hidden])');assert.equal(await broken.locator('#tw-error a').getAttribute('href'),'timeline-sources.html');await broken.close();check('data failure provides static recovery');
  const noJS=await browser.newContext({javaScriptEnabled:false}),staticPage=await noJS.newPage();await staticPage.goto(base+'/timeline-sources.html');assert.equal(await staticPage.locator('article').count(),1342);await noJS.close();check('the complete static edition remains available without JavaScript');
  const fixtureContext=await browser.newContext(),fixturePage=await fixtureContext.newPage();
  const dataset=await (await context.request.get(base+'/data/timeline/sources.json')).json(),supporting=dataset.sources.slice(0,2).map(r=>r.id);
  const fixture={version:1,collections:[],claims:[],revisions:[],events:[{id:'test-event',status:'approved',title:'Automated test fixture',summary:'Fixture verifies year precision and source bundles only.',sourceIds:supporting,themes:['health-care'],review:{reviewer:'Test fixture',reviewedAt:'2026-10-03'},eventTime:{start:'2025-01-01',end:null,precision:'year',label:'2025',rationale:'Synthetic date evidence for automated tests',sourceIds:supporting}}],relationships:supporting.map((id,i)=>({id:'test-relation-'+i,from:id,to:'test-event',type:'reports-on',status:'approved',explanation:'Synthetic test relationship',evidence:[{sourceId:id,locator:'Synthetic fixture'}],review:{reviewer:'Test fixture',reviewedAt:'2026-10-03'}}))};
  await fixturePage.route('**/data/timeline/editorial.json',r=>r.fulfill({json:fixture}));await fixturePage.goto(base+'/timeline.html?mode=events');await fixturePage.waitForFunction(()=>document.querySelector('#tw-results-title').textContent==='1 reviewed events');await fixturePage.locator('#tw-records h3 a').click();assert.ok((await fixturePage.locator('#tw-detail').innerText()).includes('year'));await fixturePage.locator('[data-save-event]').click();assert.equal(await fixturePage.locator('#tw-packet-count').innerText(),'2');await fixtureContext.close();check('approved-event fixture keeps date precision and supporting source bundles');
  assert.deepEqual(errors,[]);check('no timeline runtime errors');
  fs.writeFileSync('/tmp/eog-timeline-browser-result.json',JSON.stringify({passed:true,checks:passed,widths:[320,390,430,768,1280,1440],errors,imageRequests:remote.length},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
